name: Backend CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-gate:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Generate Prisma Clients
      run: |
        npx prisma generate --schema=services/products-service/src/prisma/schema.prisma
        npx prisma generate --schema=services/orders-service/src/prisma/schema.prisma
        
    - name: Run Linter
      run: npm run lint:all
      
    - name: Build Modules
      run: npm run build:all
        
    - name: Run Unit Tests
      run: npm run test:all

    - name: Simulate Deployment (Docker Build)
      run: |
        docker build -t ecommerce/products-service -f Dockerfile.products .
        docker build -t ecommerce/orders-service -f Dockerfile.orders .

  release:
    name: Generate Changelog & Bump Version
    needs: quality-gate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Run Semantic Release
        run: npx commit-and-tag-version
        
      - name: Push Git Tags and Changelog
        run: git push --follow-tags origin main
